### ISSUE TITLE
Datos de afluencia estaciones del metro

### ISSUE THREAD

**Issue by jgarciad** [jgarciad/proyecto_final_equipo_3#10]
Generar un archivo csv donde se puedan consultar los datos de afluencia por cada estación del metro.

**Comment by marcoyel21** [comment]
Hola, he subido una version limpia de lalista de nodos y edges en la carpeta gephi, favor de basarse en esa por cuestion de homologar nombres @AlineLPL

**Comment by AlineLPL** [comment]
Hola @marcoyel21, de acuerdo, adapto los nombres a esos nodos, mil gracias !

**Comment by jgarciad** [comment]
Gracias @marcoyel21, cierro el issue como completado
