### ISSUE TITLE
Generar grafos

### ISSUE THREAD

**Issue by jgarciad** [jgarciad/proyecto_final_equipo_3#12]
Generar un grafos donde se pueda visualizar la red del metro.

**Comment by marcoyel21** [comment]
Se opto por usar Gephi debido a que mejora la calidad de las visualizaciones y nos permite tener mayor profunidad.
Aun quedan unos pequeños detalles: por resolver como algunos errores en la importación de datos
Además se añaden la lista de nodos y edges limpia debido a que habia errores en cuanto a nombres en ambas listas.
