### ISSUE TITLE
Explicación del algoritmo 

### ISSUE THREAD

**Issue by jgarciad** [jgarciad/proyecto_final_equipo_3#13]
Explicar el algoritmo y su funcionamiento de manera teórica.

**Comment by marcoyel21** [comment]
Se añade una descripción muy sencilla, podriamos añadir un pseudocódigo del algoritmo pero como prefieran.

Se añadió lo siguiente:

Algoritmo Dijkstra

El algoritmo de Dijkstra sirve para encontrar el camino más corto entre dos nodos de un grafo. Encuentra la distancia más corta entre un nodo particular y todos los demás nodos, creando un "arbol de distancia mas corta". Es de gran utilidad por ejemplo para los casos de redes muy pobladas (piensen en cadenas de suministro, redes sociales etc) y se usa por ejemplo en los GPS.

Como curiosidad, fue inventado por  Dr. Dijkstra durante una cita en la que se preguntaba cuál era la mejor manera de llegar de Rotterdam a Groningen. Además menciona que le tomo diseñarlo 20 minutos y que parte escencial de su exito es su simpleza; menciona que no usó lapiz y pluma, de lo contrario,menciona, se hubiese vuelto innecesariamente más complejo.

Algoritmo:

Se comienza en el nodo fuente y se va analizando cada distancia al nodo adyacente.
Se almacena la distancia más corta encontrada hasta el momento
Se continua con el siguiente nodo más adjacente, se evalúa la distancia y se actualizan las distancias mínimas en caso de econtrarse una distancia más corta.
Se repite hasta visitar el nodo más lejano.

Comentarios: 

+ Es masomenos un algoritmo de fuerza bruta pues tiene que visitar toda la gráfica (en el peor de los casos) partiendo de un nodo para conocer la distancia más corta.
+ Los pesos de las aristas tienen que ser positivos de lo contrario no funciona aunque podemos resolver esto si hacemos una transformación a los pesos (como multiplicar al cuadrádo o tomar el valor absoluto dependiendo del contexto)

Fuentes
https://es.wikipedia.org/wiki/Algoritmo_de_Dijkstra
https://www.freecodecamp.org/news/dijkstras-shortest-path-algorithm-visual-introduction/

**Comment by jgarciad** [comment]
Marco, 

Tal y como lo platicamos, subamos la explicación al reporte y en el commit asignemos el avance a esta tarea y a la tarea #21 para poder dar el seguimiento correcto. Adicional, en el reporte agregar más detalle, me parece que el resumen que pones aquí esta bien para el readme de este repositorio en el cual intentaré ser un poco más conciso.

**Comment by jgarciad** [comment]
Como se acordó equipo, estamos avanzando en la reformulación del problema de acuerdo a lo comentado por Erick.

**Comment by jgarciad** [comment]
Esta tarea se completo desde hace unos días, sólo restaba actualizar el issue.
