### ISSUE TITLE
Armado matriz de distancias

### ISSUE THREAD

**Issue by jgarciad** [jgarciad/proyecto_final_equipo_3#3]
Generar una función que permita el armado de una matriz de adyacencias en donde cada renglón y columna representa las distintas estaciones del metro y al interior la distancia en metros de cada estación. Subir código en notebook de python.

**Comment by jgarciad** [comment]
Perfecto Sandra. Veo que se pudo armar la matriz sin problema. Por ahora no cierro este issue hasta tener la próxima discusión como equipo.

**Comment by sparkieth** [comment]
Hola Jorge, no sería mejor que cierres este issue?

**Comment by jgarciad** [comment]
Hola Sandy, correcto, ya estamos ok con el tema de la matriz.
