### ISSUE TITLE
Explicación de los datos

### ISSUE THREAD

**Issue by jgarciad** [jgarciad/proyecto_final_equipo_3#8]
Explicar la fuente de los datos y cuál es la idea de cómo trabajarlos.

**Comment by sparkieth** [comment]
Hola Jorge, oye creo que esto ya está en el reporte? Consideras que debamos poner algo adicional? Saludos

**Comment by jgarciad** [comment]
Hola Sandra, de acuerdo. Aún toca revisar temas de redacción pero eso se sigue trabajando mientras el issue 21 este abierto. Cierro esta tarea como completada.
